resource_types:
- name: staticfile
  type: docker-image
  source:
    repository: christianang/staticfile-resource

resources:
- name: configuration
  type: staticfile
  source:
    filename: config.yml
    data: |
      hello: world

jobs:
- name: print-config
  plan:
  - get: configuration
  - task: print-config
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: cat
        args:
        - configuration/config.yml
