---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang

inputs:
  - name: staticfile-resource

outputs:
  - name: workspace

run:
  path: staticfile-resource/ci/tasks/prepare-workspace/task.sh
